### ISSUE TITLE
Individual parking spaces shouldn't need reports

### ISSUE THREAD

**Issue by RedAuburn** [sozialhelden/wheelmap-frontend#394]
![image](https://github.com/sozialhelden/wheelmap-frontend/assets/26939824/62437587-8e6c-49b7-bc0f-5eb735d4b02b)

https://beta.wheelmap.org/way/1019518006

better to only request for parking areas

**Comment by map-per** [comment]
And even vor `amenity=parking` adding wheelchair is not common (only 1.6% off all `amenity=parking` have `wheelchair=*`) and the meaning of `wheelchair` in this context is neither defined nor obvious.
It's way more common to map the availability of disabled parking spaces with `capacity:disabled=*`([Wiki](https://wiki.openstreetmap.org/wiki/Key:capacity:disabled)) or `parking_space=disabled`([Wiki](https://wiki.openstreetmap.org/wiki/Tag:parking_space%3Ddisabled)).

**Comment by opyh** [comment]
Thanks for this report. You're right, this does not make sense. It would make more sense to have the whole parking facility marked instead of single parking lots.

Here is how it looks on OSM:

<img width="973" alt="image" src="https://github.com/sozialhelden/wheelmap-frontend/assets/192912/ae22d421-4fc5-4e3d-acca-963000e8d6b7">

As the `wheelchair` tag makes less sense than `capacity:disabled` and use of other tags than `wheelchair` isn't supported in Wheelmap yet, we will remove the capability of tagging parking facilities with `wheelchair` tags for now, and will rely on the `capacity:disabled` (with a fallback on `wheelchair`, if existing) for displaying parking accessibility instead. Additionally, we'll interpret and display the `capacity:disabled` and the `access` tag (see commit b13ee8ea1bb06bfc01c30b35009a4a93140a794f) and display a more exact type of parking facility as place name (e.g. "Rooftop Parking" or "Underground parking").

This is how it looks for a supermarket parking facility:

![image](https://github.com/sozialhelden/wheelmap-frontend/assets/192912/0f42cc6f-9ecb-42e5-9c5b-d3bec5550f7d)

If you want to see parking information in Wheelmap, you'll need to add the tags in other OSM editors for now.

The parking lots you mentioned in your comment will not be displayed as OSM-sourced place until the [way](https://www.openstreetmap.org/way/22721236#map=19/51.47910/-0.00924) gets either a `wheelchair` or a `capacity:disabled` tag. You will, however, find the parking facility on the map as place-of-interest of our other sources (https://feature-osm-parking.wheelmap.tech/nodes/kQGhWGkxpeKxqNELc, https://feature-osm-parking.wheelmap.tech/nodes/e7D72784EZWW2TTvL).

Feel free to check the [https://feature-osm-parking.wheelmap.tech](`feature/osm-parking` branch deployment) - this will land in production soon :)

**Comment by opyh** [comment]
This is now in production ([see example](https://wheelmap.org/way/87376357)). Feel free to reopen this issue if you see something that is not right.

**Comment by opyh** [comment]
Relevant code for determining shown infos about parking facilities: https://github.com/sozialhelden/wheelmap-frontend/blob/main/src/components/NodeToolbar/AccessibilitySection/WheelchairAndToiletAccessibility.tsx#L208
